EcoShrimp.Client/Areas/Client/Views/Shared/Components/ClientFooter/ClientFooterViewComponent.cs
using EcoShrimp.Data;
using Microsoft.AspNetCore.Mvc;

namespace EcoShrimp.Client.Areas.Client.Views.Shared.Components.Footer
{
	public class ClientFooterViewComponent : ViewComponent
	{
		protected readonly ApplicationDbContext _DbContext;

		public ClientFooterViewComponent(ApplicationDbContext DbContext)
		{
			_DbContext = DbContext;
		}
		public async Task<IViewComponentResult> InvokeAsync()
		{
			var shrimp = _DbContext.AppShrimps.FirstOrDefault();

			return View(shrimp);
		}
	}
}

EcoShrimp.Client/Areas/Client/Views/Shared/Components/MainNavBar/MainNavBarViewComponent.cs
using EcoShrimp.Data;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace EcoShrimp.Client.Areas.Client.Views.Shared.Components.MainNavBar
{
	public class MainNavBarViewComponent : ViewComponent
	{
		protected readonly ApplicationDbContext _DbContext;
		public MainNavBarViewComponent(ApplicationDbContext DbContext)
		{
			_DbContext = DbContext;
		}
		public async Task<IViewComponentResult> InvokeAsync()
		{

			ClaimsIdentity identity = (ClaimsIdentity)User.Identity!;
			var IdClaim = identity.FindFirst("ID")?.Value;
			int IdFarm = int.Parse(IdClaim);
			TempData["farm"] = _DbContext.AppFarms.FirstOrDefault(x => x.Id == IdFarm);


			var idGroupClaim = HttpContext.User.FindFirst("IdGroup")?.Value;

			var navBar = new NavBarViewModel();
			navBar.Items.AddRange(new MenuItem[]
			{
				new MenuItem
				{
					Action = "Index",
					Controller = "ClientHome",
					DisplayText = "Trang chủ",
					Icon = "fas fa-home",
					//Permission = AuthConst.AppAmenity.VIEW_LIST, 
				},
				new MenuItem
				{
					Action = "Index",
					Controller = "ClientFarm",
					DisplayText = "Trang trại",
					Icon = "fas fa-suitcase",
					//Permission = AuthConst.AppAmenity.VIEW_LIST,
				},
				new MenuItem
				{
					Action = "Index",
					Controller = "ClientPond",
					DisplayText = "Vuông nuôi",
					Icon = "fas fa-expand",
					//Permission = AuthConst.AppAmenity.VIEW_LIST,
				},
				new MenuItem
				{
					Action = "Index",
					Controller = "ClientHistory",
					DisplayText = "Lịch sử nuôi trồng",
					Icon = "fas fa-history",
					//Permission = AuthConst.AppAmenity.VIEW_LIST,
				},
				new MenuItem
				{
					Action = "SendCode",
					Controller = "ClientAccount",
					DisplayText = "Đổi mật khẩu",
					Icon = "fas fa-lock",
					//Permission = AuthConst.AppAmenity.VIEW_LIST,
				},


			});
			//TempData["Hotel"] = _HotelDbContext.AppHotel.Where(x => x.IdGroup == int.Parse(idGroupClaim)).FirstOrDefault();
			//if (TempData["Hotel"] as AppHotels == null)
			//{
			//	return View("Index");
			//}


			return View(navBar);
		}
	}
}

EcoShrimp.Client/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace EcoShrimp.Client.Controllers
{
	public class ContactController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

EcoShrimp.Client/Controllers/ProductController.cs
using AutoMapper;
using EcoShrimp.Client.Controllers.Base;
using EcoShrimp.Client.ViewModels.Request;
using EcoShrimp.Data;
using EcoShrimp.Data.Entities;
using EcoShrimp.Share.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.Mail;
using X.PagedList.Extensions;

namespace EcoShrimp.Client.Controllers
{
	public class ProductController : ShrimpControllerBase
	{
		public ProductController(ApplicationDbContext DbContext, IMapper mapper) : base(DbContext, mapper)
		{
		}

		public IActionResult Index(string keyword, int page = 1, int size = DEFAULT_PAGE_SIZE)
		{
			var products = _DbContext.AppProducts.Include(x => x.appImges).Where(x => x.Status != Status.Deleted)
										.OrderBy(x => x.SortOrder).AsQueryable();

			if (keyword != null)
			{
				keyword = keyword.Trim().ToUpper();
				products = products.Where(x => x.Name.ToUpper().Contains(keyword) || x.Desc.ToUpper().Contains(keyword));
				TempData["searched"] = "searched";
			}

			TempData["Products"] = _DbContext.AppProducts.Include(x => x.appCategory)
											.Take(3)
											.Include(x => x.appImges).ToList();

			// Trả về view với dữ liệu phân trang
			return View(products.ToPagedList(page, size));
		}


		public IActionResult Detail(int id)
		{
			if (id <= 0)
			{
				SetErrorMesg("Đã xảy ra lỗi trong quá trình xử lí!!");
				return RedirectToAction("Index", "Home");
			}

			var product = _DbContext.AppProducts.Include(x => x.appCategory)
											.Include(x => x.appImges).FirstOrDefault(x => x.Id == id);
			if (product == null)
			{
				SetErrorMesg("Đã xảy ra lỗi trong quá trình xử lí!!");
				return RedirectToAction("Index", "Home");
			}

			TempData["Products"] = _DbContext.AppProducts.Include(x => x.appCategory)
											.Where(x => x.Id != product.Id)
											.Take(8)
											.Include(x => x.appImges).ToList();

			return View(product);
		}

		[HttpPost]
		public IActionResult Requests(RequestVM model)
		{
			if (!ModelState.IsValid)
			{
				var errors = ModelState.Values
					.SelectMany(v => v.Errors)
					.Select(e => e.ErrorMessage)
					.ToList();

				SetErrorMesg(string.Join("\n", errors)); // Gộp tất cả lỗi thành một chuỗi

				return Redirect(Request.Headers["Referer"].ToString() ?? "/");
			}

			// Tạo đối tượng yêu cầu
			var request = new AppRequests
			{
				CompanyName = model.CompanyName,
				Email = model.Email,
				Phone = model.Phone,
				Address = model.Address,
				Content = model.Content,
				CreatedDate = DateTime.Now,
				Status = RequestStatus.Pending
			};

			// Lưu vào Cơ sở dữ liệu
			_DbContext.Add(request);
			_DbContext.SaveChanges();

			// Nội dung email
			string content = $@"
							<div class=""container bg-secondary d-flex justify-content-center"">
								<div class=""bg-light mt-1 rounded-2 p-3"" style=""width: 1200px"">
									<div class=""row px-4"">
										<div class=""col p-0"">
											<div class=""row"">Thân gửi {model.CompanyName},</div>
											<div class=""row"">
												<span class=""p-0 col-auto fw-bold"" style=""color:#c88321"">Booking.com</span>
												<div class=""col-auto ps-1"">vừa nhận được một yêu cầu từ khách hàng liên quan đến dịch vụ của bạn trên <span style=""color:#c88321"">EcoShrimp.com</span></div>
											</div>
											<div class=""row mt-2""><i class=""p-0"">Thông tin yêu cầu:</i></div>
											<div class=""row ms-3"">Tên công ty: {model.CompanyName}</div>
											<div class=""row ms-3"">Email: {model.Email}</div>
											<div class=""row ms-3"">Số điện thoại: {model.Phone}</div>
											<div class=""row ms-3"">Địa chỉ: {model.Address}</div>
											<div class=""row ms-3"">Nội dung yêu cầu: {model.Content}</div>
											<div class=""row mt-2""><i class=""p-0""><span class=""text-danger"">Ghi chú:</span> Vui lòng liên hệ qua thông tin trên để phản hồi yêu cầu từ khách hàng.</i></div>
											<div class=""row mt-2"">
												Chúng tôi đã nhận được thông tin yêu cầu của bạn và sẽ xử lý nhanh chóng. Đội ngũ của chúng tôi sẽ liên hệ lại với bạn trong thời gian sớm nhất để hỗ trợ và giải đáp mọi thắc mắc. Chúng tôi rất trân trọng sự tin tưởng và hợp tác của bạn. Cảm ơn bạn đã lựa chọn dịch vụ của chúng tôi!
											</div>
											<div class=""row mt-2"">Trân trọng cảm ơn,</div>
											<div class=""row"">EcoShrimp.com</div>
										</div>
									</div>
								</div>
							</div>
							";

			// Thông tin người gửi email
			var username = "quocduyctvn@gmail.com";
			var password = "ylya rfag tclg nhae";
			var host = "smtp.gmail.com";
			var port = 587;
			var fromEmail = "quocduyctvn@gmail.com";

			// Tạo đối tượng MailMessage để gửi mail
			MailMessage message = new MailMessage();
			message.From = new MailAddress(fromEmail); // Người gửi email
			message.To.Add(model.Email); // Người nhận mail (từ model, có thể là khách hàng)
			message.Subject = "Yêu cầu liên hệ từ khách hàng trên EcoShrimp.com";
			message.IsBodyHtml = true;
			message.Body = content;

			// Tạo đối tượng SmtpClient để cấu hình gửi mail
			SmtpClient mailClient = new SmtpClient
			{
				EnableSsl = true,
				UseDefaultCredentials = false,
				Credentials = new System.Net.NetworkCredential(username, password),
				Host = host,
				Port = port
			};

			// Gửi email
			try
			{
				mailClient.Send(message);
				SetSuccessMesg("Yêu cầu của bạn đã được gửi đi thành công!");
			}
			catch (Exception ex)
			{
				SetErrorMesg($"Có lỗi xảy ra trong quá trình gửi email: {ex.Message}");
			}

			return Redirect(Request.Headers["Referer"].ToString() ?? "/");
		}



	}
}

EcoShrimp.Client/Views/Shared/Components/Contact/ContactViewComponent.cs
using EcoShrimp.Data;
using Microsoft.AspNetCore.Mvc;

namespace EcoShrimp.Client.Views.Shared.Components.Contact
{
	public class ContactViewComponent : ViewComponent
	{

		protected readonly ApplicationDbContext _DbContext;
		public ContactViewComponent(ApplicationDbContext DbContext)
		{
			_DbContext = DbContext;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			TempData["shrimp"] = _DbContext.AppShrimps.FirstOrDefault();
			return View();
		}
	}
}

EcoShrimp.Client/Views/Shared/Components/Footer/FooterViewComponent.cs
using EcoShrimp.Data;
using Microsoft.AspNetCore.Mvc;

namespace EcoShrimp.Client.Views.Shared.Components.Footer
{
	public class FooterViewComponent : ViewComponent
	{

		protected readonly ApplicationDbContext _DbContext;
		public FooterViewComponent(ApplicationDbContext DbContext)
		{
			_DbContext = DbContext;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var shrimp = _DbContext.AppShrimps.FirstOrDefault();
			TempData["policies"] = _DbContext.AppPolicies.Take(4).ToList();
			return View(shrimp);
		}
	}
}

EcoShrimp.Client/Views/Shared/Components/Header/HeaderViewComponent.cs
using EcoShrimp.Data;
using Microsoft.AspNetCore.Mvc;

namespace EcoShrimp.Client.Views.Shared.Components.Header
{
	public class HeaderViewComponent : ViewComponent
	{

		protected readonly ApplicationDbContext _DbContext;
		public HeaderViewComponent(ApplicationDbContext DbContext)
		{
			_DbContext = DbContext;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var shrimp = _DbContext.AppShrimps.FirstOrDefault();
			return View(shrimp);
		}
	}
}

EcoShrimp.Client/Views/Shared/Components/News/NewsViewComponent.cs
using EcoShrimp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EcoShrimp.Client.Views.Shared.Components.News
{
	public class NewsViewComponent : ViewComponent
	{

		protected readonly ApplicationDbContext _DbContext;
		public NewsViewComponent(ApplicationDbContext DbContext)
		{
			_DbContext = DbContext;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var device = _DbContext.AppNews
										.Include(x => x.appCateNew)
										.Take(3)
										.ToList();
			return View(device);
		}
	}
}

EcoShrimp.Client/Views/Shared/Components/Product/ProductViewComponent.cs
using EcoShrimp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EcoShrimp.Client.Views.Shared.Components.Device
{
	public class ProductViewComponent : ViewComponent
	{

		protected readonly ApplicationDbContext _DbContext;
		public ProductViewComponent(ApplicationDbContext DbContext)
		{
			_DbContext = DbContext;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var device = _DbContext.AppProducts
										.Include(x => x.appImges)
										.Include(x => x.appCategory)
										.Take(3)
										.ToList();
			return View(device);
		}
	}
}

EcoShrimp.Client/Views/Shared/Components/Footer/Default.cshtml
@using EcoShrimp.Data.Entities
@model EcoShrimp.Data.Entities.AppShrimp
@{
	var policies = TempData["policies"] as List<AppPolicies>;
}

<footer class="footer-area mt-4">
	<!--Start Footer-->
	<div class="footer">
		<div class="container-fluid" style="padding: 0 90px">
			<div class="row text-right-rtl">
				<!--Start single footer widget-->
				<div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 wow animated fadeInUp" data-wow-delay="0.1s">
					<div class="single-footer-widget marbtm50">
						<div class="our-company-info">
							<div class="footer-logo">
								<a href="index-2.html"><img src="@Model.LogoUrl" alt="" /></a>
							</div>
						</div>
					</div>
				</div>
				<!--End single footer widget-->
				<!--Start single footer widget-->
				<div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 wow animated fadeInUp" data-wow-delay="0.1s">
					<div class="single-footer-widget marbtm50">
						<div class="our-company-info">
							<div class="title">
								<h3>về chúng tôi</h3>
								<div class="decor">
									<img src="~/assets-template/images/shape/decor.png" alt="">
								</div>
							</div>
							<div class="our-company-info-list">
								<ul>
									<li><span class="icon-check-mark"></span>Địa chỉ: @Model.Address</li>
									<li><span class="icon-check-mark"></span>Hotline: @Model.Phone</li>
									@if (Model.SubPhone != null)
									{
										<li><span class="icon-check-mark"></span>Phòng kỹ thuật: @Model.SubPhone</li>
									}
									<li><span class="icon-check-mark"></span>Email: @Model.Email</li>
								</ul>
							</div>
						</div>
					</div>
				</div>

				<div class="col-xl-2 col-lg-6 col-md-6 col-sm-12 wow animated fadeInUp" data-wow-delay="0.1s">
					<div class="single-footer-widget marbtm50">
						<div class="our-company-info">
							<div class="title">
								<h3>
									DANH MỤC
								</h3>
								<div class="decor">
									<img src="~/assets-template/images/shape/decor.png" alt="">
								</div>
							</div>
							<div class="our-company-info-list">
								<ul>
									<li>
										<a asp-action="Index" class="text-light">
											<span class="icon-check-mark"></span>Trang chủ
										</a>
									</li>
									<li>
										<a asp-action="Index" asp-controller="Product" class="text-light">
											<span class="icon-check-mark"></span>Sản phẫm
										</a>
									</li>
									<li>
										<a asp-action="Index" asp-controller="News" class="text-light">
											<span class="icon-check-mark"></span>Tin tức
										</a>
									</li>
									<li>
										<a asp-action="Index" asp-controller="Contact" class="text-light">
											<span class="icon-check-mark"></span>Liên hệ
										</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 wow animated fadeInUp" data-wow-delay="0.1s">
					<div class="single-footer-widget marbtm50">
						<div class="our-company-info">
							<div class="title">
								<h3>
									Chính sách của chúng tôi
								</h3>
								<div class="decor">
									<img src="~/assets-template/images/shape/decor.png" alt="">
								</div>
							</div>
							<div class="our-company-info-list">
								<ul>
									@foreach (var item in policies)
									{
										<a asp-action="Detail" asp-route-id="@item.Id" asp-controller="Policies" class="text-light">
										<li><span class="icon-check-mark"></span>@item.Name</li>
										</a>
									}
								</ul>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
	<!--End Footer-->

</footer>